services:
  amplymate:
    image: amplymate_v1.0

    environment:
      # Sequence mismatch in cutadapt
      MISMATCH_rate: 0.2
      # Quality control
      MIN_LEN: 100
      MAXEE: 2
      TRUNCLEN: 240
      TRUNCLEN2: 210
      MINQ: 10
      # Reference database to annotate taxonomy
      REF_DB: '{
        "515f":"silva",
        "its":"unite"
        }'
      # OTU level
      MAX_th: 1
      MIN_th: 0.96
      BY: 0.02
      # Filtering taxonomy
      TARGET_TAXA: '{
        "515f":["Bacteria", "Archea"],
        "its":"Fungi"
        }'

      # Output directory name in container
      SCRIPT_PATH: /_SCRIPTS
      BASE_PATH: "/data"
      RAW_FASTQ: "/data/BCLConvert/fastq"
      DEMUX_BY_PRIMER: "/data/01_DEMUX_BY_PRIMER"
      TRIMMING: "/data/02_TRIMMING"
      QUALITY_CONTROL: "/data/03_FILT_SEQ"
      DENOISING: "/data/04_DENOISING"
      ANNOTATION: "/data/05_ANNOTATION"
      CLUSTERING: "/data/06_CLUSTERING"

      EVAL_SUMMARY: "/data/EVAL"
      EVAL_DEMUX: "/data/EVAL/DEMUX_PRIMER"
      EVAL_TRIMMING: "/data/EVAL/TRIMMING"
      EVAL_FILT: "/data/EVAL/FILTERING"
      THREADS: 32

      PASSWORD: ${RSTUDIO_PASSWORD:-rstudio}
      DISABLE_AUTH: "false"

    build:
      context: .
      dockerfile: amplymate.Dockerfile
      args:
        VSEARCH: "2.30.6"
        CUTADAPT: "5.2"
        BIOC: "3.22"
        SEQKIT: "2.13.0"
        FASTQC: "0.12.1"

        UID: ${UID:-1000}
        GID: ${GID:-1000}

    volumes:
      - type: bind
        source: ${MOUNT_PATH:-.}
        target: /data

      - type: bind
        source: ${GENOME_DB:-${HOME}/db}
        target: /db

      - type: bind
        source: ${SCRIPT_PATH:-./amplymate/scripts}
        target: /_SCRIPTS

    container_name: amplymate

    working_dir: /data

    ports:
      - "8787:8787"

    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc:
        soft: 32768
        hard: 32768

    stdin_open: true
    tty: true
